class FilteringRepository:
    def get_selected(self, item_id: int, name: str | None = None) -> bool:
        ...

    def set_selected(self, item_id: int, name: str | None, selected: bool) -> None:
        ...

    def list_selected(self) -> list[tuple[int | None, str | None]]:
        ...

    def count_selected(self) -> int:
        ...
