from annotation_tool.core.models import LabelingStatusData
from annotation_tool.annotation.figure_controller import FigureController


class LabelingSession:
    def item_count(self) -> int:
        ...

    def current_item_id(self) -> int:
        ...

    def current_image_path(self) -> str:
        ...

    def status(self) -> LabelingStatusData:
        ...

    def controller(self) -> FigureController:
        ...

    def load_current_item(self) -> None:
        ...

    def save_current_item(self) -> None:
        ...

    def go_to_item(self, item_id: int) -> None:
        ...

    def next_item(self) -> None:
        ...

    def previous_item(self) -> None:
        ...

    def set_active_label_by_hotkey(self, hotkey: str) -> None:
        ...

    def toggle_trash(self) -> None:
        ...

    def toggle_figures_visibility(self) -> None:
        ...

    def toggle_review_labels_visibility(self) -> None:
        ...

    def toggle_label_names(self) -> None:
        ...

    def toggle_object_size(self) -> None:
        ...

    def toggle_degraded_preview(self) -> None:
        ...

    def copy_from_previous_item(self) -> None:
        ...

    def close(self) -> None:
        ...
